version: '3'
services:

#  reactive-spring-forex-trade:
#    build:
#      dockerfile: Dockerfile
#      context: .
#    ports:
#      - 8080:8080
#    environment:
#      - APP_FOREX-RATE-API-URL=http://json-mock-server:80
#    depends_on:
#      - json-mock-server

  json-mock-server:
    image: clue/json-server
    ports:
      - 3000:80
    volumes:
      - ./mock-server/db.json:/data/db.json