apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: reactive-spring-forex-trade
build:
  artifacts:
    - image: zarinfam/reactive-spring-forex-trade
      context: .
      docker:
        dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
      - k8s