apiVersion: apps/v1           # API version
kind: Deployment              # Type of kubernetes resource
metadata:
  name: forex-trade-api    # Name of the kubernetes resource
  labels:                     # Labels that will be applied to this resource
    app: forex-trade-api
spec:
  replicas: 1                 # No. of replicas/pods to run in this deployment
  selector:
    matchLabels:              # The deployment applies to any pods mayching the specified labels
      app: forex-trade-api
  template:                   # Template for creating the pods in this deployment
    metadata:
      labels:                 # Labels that will be applied to each Pod in this deployment
        app: forex-trade-api
    spec:                     # Spec for the containers that will be run in the Pods
      initContainers:
      - name: mysql-db-ready
        image: busybox:1.31
        command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z mysql 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL DB Server has started";']
      containers:
      - name: forex-trade-api
        image: zarinfam/reactive-spring-forex-trade
        ports:
          - name: http
            containerPort: 8080 # The port that the container exposes
        env:                  # Environment variables supplied to the Pod
        - name: SPRING_R2DBC_USERNAME # Name of the environment variable
          valueFrom:          # Get the value of environment variable from kubernetes secrets
            secretKeyRef:
              name: mysql-user-pass
              key: username
        - name: SPRING_R2DBC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-user-pass
              key: password
        - name: SPRING_R2DBC_URL
          valueFrom:
            secretKeyRef:
              name: mysql-db-url
              key: url
        - name: APP_FOREX-RATE-API-URL
          valueFrom:
            secretKeyRef:
              name: rate-api-url
              key: url
---
apiVersion: v1                # API version
kind: Service                 # Type of the kubernetes resource
metadata:                     
  name: forex-trade-api    # Name of the kubernetes resource
  labels:                     # Labels that will be applied to this resource
    app: forex-trade-api
spec:                         
  type: ClusterIP                # Exposes the service by opening a port on each node
  selector:
    app: forex-trade-api   # The service exposes Pods with label `app=forex-trade-api`
  ports:                      # Forward incoming connections on port 8080 to the target port 8080
  - name: http
    port: 8080
    targetPort: 8080
